### ISSUE TITLE
Pre-auths not in event list

### ISSUE THREAD

**Issue by everhardt** [Mangopay/mangopay#10]
When I request events in the API, pre-authorizations are never included. Why aren't they returned?

**Comment by hobailey** [comment]
Hi @everhardt, there are infact no events created for preauths, so you will not get hooks, nor find them in the event list.

**Comment by everhardt** [comment]
Thanks for the swift reply. So there is no way to get insight in reasons for failed preauths, other than logging it in our own systems?

**Comment by hobailey** [comment]
Well preauths fail in realtime (ie at the moment of doing the preauth) so you can see the failure and reason straight away in the response of the API call. Although to be fair, if you're doing preauths that require 3DS, then it could indeed fail 15 minutes later if the user does not complete the 3DS step. But if they *do* complete this step, they'll come back via your `SecureModeReturnURL` so you can be notified that way.
It's not perfect I appreciate, which is why we'll be indeed adding events/hooks for these objects soon.

**Comment by everhardt** [comment]
Great, thanks!
