### ISSUE TITLE
Discrepancies between fetching a pay in and user transactions

### ISSUE THREAD

**Issue by ldesgrange** [Mangopay/mangopay#13]
Hi,

I created a pay in on a user wallet and fetched it using `payins/{id}`. Then when I fetch it through the user's transactions (`users/{id}/transactions`) I don't get the same result.
The following fields are missing:
`PaymentType`, `ExecutionType`, `SecureMode`, `CardId`, `SecureModeReturnURL`, `SecureModeRedirectURL`, `SecureModeNeeded`, `StatementDescriptor`

Without `PaymentType` field the pay in type (bank wire, card…) is missing, so casting the pay in to a concrete specific class is not possible.

Is there any reason those fields are not returned? Could they be provided?

Regards,

Laurent.

**Comment by hobailey** [comment]
Hi @ldesgrange, in all transactions lists, only the base transaction parameters are shown I'm afraid. This is because there are great number of different transactions types and it greatly simplifies the lists (and makes them easier for the SDKs to handle).
This is not something we're thinking of changing at this time I'm afraid.

**Comment by hobailey** [comment]
This is true, but unfortunately this is a limitation of our API at present. We'll be launching later this week a reporting service allowing you to download huge transaction lists with all this info included :-)
