### ISSUE TITLE
Filtering transactions by type returns transactions from other types

### ISSUE THREAD

**Issue by ldesgrange** [Mangopay/mangopay#21]
Hi,

I'm retrieving the list of PAYINs for a given user (`/users/<UserId>/transactions/`) but the returned list also contains a REFUND PAYOUT. 

Refund transactions are not listed as valid filters, shouldn't they be added as such and not returned when filtering for other transaction types?

Laurent.

**Comment by hobailey** [comment]
Hey @ldesgrange, thanks for your query. If I understand your question correctly, you're filtering your transaction list using the `Type` filter (which is "PAYIN") but you're getting refunds showing up? If so, you can use the `Nature` filter to say that you only want "REGULAR" transactions - other options could be "REFUND", "REPUDIATION" or "SETTLEMENT" ([more info](https://docs.mangopay.com/endpoints/v2.01/transactions#e262_list-a-users-transactions)).
Remember that if you want to run specific reports (and use multiple filter criteria etc), you can using the new [reporting features](https://docs.mangopay.com/endpoints/v2.01/reporting#e824_the-report-object) (easiest to use via the [Dashboard](https://docs.mangopay.com/guide/dashboard)).
If you have any further support queries, don't hesitate to contact us via [this page](https://docs.mangopay.com/contact) - this repo is for known issues only rather than general tech support :-)

**Comment by ldesgrange** [comment]
OK, didn't saw the `Nature` filter before, but it still seems strange that I receive a transaction of type PAYOUT (and REFUND nature) when filtering for transactions of type PAYIN.

**Comment by hobailey** [comment]
@ldesgrange - this does indeed sound odd. Could you send to our support team your ClientId and the UTC time you did the API call so we can take a closer look please?
